### ISSUE TITLE
Doesn't work with AirPods controls

### ISSUE THREAD

**Issue by zdlo** [quentinlesceller/macmediakeyforwarder#1]
Works fine with the media keys, but AirPods controls act as before.

**Comment by quentinlesceller** [comment]
Hi @zdlo. As I've just forked it to Mac it m1 compatible I've no idea about AirPods control. However, fwiw, it currently works with my EarPods button.

**Comment by zdlo** [comment]
> However, fwiw, it currently works with my EarPods button.

Not sure what you mean. Do you mean, when you click on your AirPods, it pauses and plays the Music app as it should, instead of a random Safari tab with YouTube on it?

I'm on 3.1.1 (build 1).
