### ISSUE TITLE
Homebrew availability

### ISSUE THREAD

**Issue by nerolite** [quentinlesceller/macmediakeyforwarder#11]
Is there any chance this fork could be added to [Homebrew](https://brew.sh/) for ease of installation and updating?

**Comment by paleite** [comment]
It's available in Homebrew already: https://formulae.brew.sh/cask/macmediakeyforwarder

**Comment by nerolite** [comment]
I wasn't aware it pointed to this fork. Thanks for clarifying. This matter is resolved.
