### ISSUE TITLE
Play/Pause occasionally doesn't work.

### ISSUE THREAD

**Issue by globalshrug** [quentinlesceller/macmediakeyforwarder#12]
I'm on Ventura 13.5.1, with macmediakeyforwarder v. 3.1.2 (build 1). This happens rarely, but the only way to fix it that I've found is to quite and reopen MMKF. The other keys (forward/backwards) seem to work fine.

Are there logs I can pull up to see what's going on, or some way I can get data from the app next time it happens so I can file a proper bug report?

**Comment by quentinlesceller** [comment]
Literally never happened to me though. I'm closing this for now but might reopen if someone else open a similar issue.

**Comment by globalshrug** [comment]
> Literally never happened to me though. I'm closing this for now but might reopen if someone else open a similar issue.

Yeah, that's why I was asking if there's a way I can send in logs or something to help. What should I do next time it happens?
