### ISSUE TITLE
Play/Pause doesn't work with EarPods

### ISSUE THREAD

**Issue by KinanLak** [quentinlesceller/macmediakeyforwarder#18]
When MMKF is launched, if I'm using the pause button on Apple EarPods, it just rapidly pauses and then resumes the music.
The pause button on keyboard works fine.

Version 3.1.1 (build 1)
MacBook Pro 14 2021
MacOS Sonoma

**Comment by HJebbour** [comment]
I have the same issue with a USB speakers.

version 3.1.2
macOS Sequoia 15.1

**Comment by quentinlesceller** [comment]
Just tested on latest Sonoma with AirPods Pro everything works as expected. I recommend that you reinstall the app.

**Comment by HJebbour** [comment]
I am running latest version of macOS Sequoia (15.1.1) and still having this issue even after multiple restart.
