### ISSUE TITLE
app doesn't show in security & privacy > automation > privacy

### ISSUE THREAD

**Issue by alainib** [quentinlesceller/macmediakeyforwarder#2]
hello

i installed it via `> brew install --cask macmediakeyforwarder`

 ==> Downloading https://github.com/milgra/macmediakeyforwarder/releases/download
 
 now i get the app in `security & privacy >  accessibility`
 but it doesn't show under 
 `security & privacy > automation > privacy`
 
 how to do it ? 
 thank you

**Comment by quentinlesceller** [comment]
You should install that one https://github.com/quentinlesceller/macmediakeyforwarder/releases.

**Comment by hellpf** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/5002221/177777818-eabe4dff-e1e6-489f-8945-1d0bd17c8dfb.png">

I'm not able to run the app, because it is not possible to allow automation under security & privacy.

**Comment by michaelhayman** [comment]
Also have the same problem, 12.5, using latest release zip (Apr '22).

<img width="915" alt="Screenshot 2022-08-07 в 11 14 19" src="https://user-images.githubusercontent.com/1134239/183283895-0da553eb-f3ae-4f04-a718-5fd97f6f3e8f.png">

**Comment by lifeonmonday** [comment]
How is that issue closed, if it's not solved at all?

**Comment by quentinlesceller** [comment]
The original issue was closed because the user used another app.
