### ISSUE TITLE
App Won't Open on Sonoma

### ISSUE THREAD

**Issue by blujjensen** [quentinlesceller/macmediakeyforwarder#20]
I've noticed ever since upgrading to Mac OS Sonoma that the app will not open or run, even after changing all of the settings in system preferences. Someone please help!
![280782207-31d59638-e4dd-4e34-8127-32b6cea1490c](https://github.com/quentinlesceller/macmediakeyforwarder/assets/155688907/03e29a10-9ea2-49c1-b9ba-161c95e11356)
![280782275-c1643276-340f-4ff7-9bd7-a84ab7857e73](https://github.com/quentinlesceller/macmediakeyforwarder/assets/155688907/4c949e26-7c12-40b3-aa6e-2bf9e9ed05f0)
![280782278-8f1d58a0-b577-4aee-893f-a3152d5bbad0](https://github.com/quentinlesceller/macmediakeyforwarder/assets/155688907/409acb05-bb2e-44d3-a2b7-d24547dcd791)

**Comment by mneuhaus** [comment]
same for me :(

**Comment by lmkunert** [comment]
same here also - unusable at this point

**Comment by Kitround** [comment]
Hello, no problems for me, everything is working great on the latest Sonoma.

**Comment by thorsteinnyngvi** [comment]
Same with regards to opening up the app - I can add it to the Accessibility section of the security settings, but I have no means to add it to the automation section. Any thoughts?

**Comment by jhagege** [comment]
> Same with regards to opening up the app - I can add it to the Accessibility section of the security settings, but I have no means to add it to the automation section. Any thoughts?

Hi same here, anyone managed to solve? Thanks!

**Comment by thorsteinnyngvi** [comment]
@jhagege I wound up installing the Spotify extension to Raycast (along with a bunch of other extensions) and my life is now 13.5% better.

**Comment by maaarcelino** [comment]
Sonoma 14.0 here. The app didn't open for me until I restarted my computer. After that I was able to open the app and select the "Prioritize Spotify" option. I didn't need to add it to the Automation section. It appeared there automatically.

**Comment by quentinlesceller** [comment]
It should work on Sonoma. Follow the instructions linked in https://github.com/quentinlesceller/macmediakeyforwarder/issues/15.
