### ISSUE TITLE
min MacOS is 12.3 not Mojave

### ISSUE THREAD

**Issue by suschizu** [quentinlesceller/macmediakeyforwarder#3]
Hello - build 3.1.1 contains as minimum version 12.3 not 10.14 

> The app itself is compatible with Mojave, but you need to add it as trusted application in order to make it function properly.

```
LSMinimumSystemVersion:
12.3
```
<img width="223" alt="Screenshot 2022-06-20 at 14 19 54" src="https://user-images.githubusercontent.com/16004333/174600392-41578ac8-445f-4ac5-a918-e4b32e84724c.png">

**Comment by quentinlesceller** [comment]
Would decreasing the min version works?

**Comment by core-code** [comment]
if it is *actually* compatible with mojave, catalina & big sur the the 'LSMinimumSystemVersion' needs to be lowered so that it can be launched on these macOS versions

if its not really compatible with 10.14, 10.15 an 11.0 then i'd recommend just changing the documentation to indicate that it requires Monterey

**Comment by alexandrehsf** [comment]
Hey. It doesn't allow me to add to the list to check as a trusted application for 10.15 (Catalina). Are any workarounds?

**Comment by quentinlesceller** [comment]
Are you sure you did right click open ?

**Comment by core-code** [comment]
> Are you sure you did right click open ?

right-click open cannot possibly have any effect here. 

as long as "12.3" is in the "LSMinimumSystemVersion" entry, it cannot be launched on any earlier system.

**Comment by quentinlesceller** [comment]
Ah yeah. Workaround is to compile
It yourself. I might lower the minimum version and release another binary next week.

**Comment by quentinlesceller** [comment]
Fixed with https://github.com/quentinlesceller/macmediakeyforwarder/commit/acd19373535c64a57a1589eafb44b8108dbb805c. See https://github.com/quentinlesceller/macmediakeyforwarder/releases/tag/v3.1.2.

**Comment by quentinlesceller** [comment]
See https://github.com/quentinlesceller/macmediakeyforwarder/issues/9. I've decided to yank this version. I recommend that you guys compile the binary version. I might revisit this later but no time atm. PR welcomes !

**Comment by quentinlesceller** [comment]
Nevermind after additional tests v3.1.2 seems to be fully working.

**Comment by suschizu** [comment]
thanks for the fix! I can confirm that the minOS is 10.14 now
