### ISSUE TITLE
Mac Media Forwarded is not working anymore.

### ISSUE THREAD

**Issue by reymillenium** [quentinlesceller/macmediakeyforwarder#4]
Mac Media Forwarded is not working anymore.

MacOS Monterey 12.5.1

<img width="328" alt="Screen Shot 2022-08-24 at 9 36 33 PM" src="https://user-images.githubusercontent.com/16376436/186554966-82aad96c-f8f2-495b-8236-b5ed1decfb03.png">

After doing exactly what that message demands (enabling Mac Media Forwarded in _Accessibility_ & _Automation_), it still doesn't works.  It worked for many years. Seems like this is the end. It's a shame.

**Comment by ShadeDream** [comment]
Had the same issue. Fixed it by opening the System Prefs -> Security & Privacy -> Accessibility and removing it there (with the minus, not just un-checking) and re-adding it. Seems to work fine after that.

**Comment by quentinlesceller** [comment]
Looks solved. Closing. Thank you @ShadeDream.
