### ISSUE TITLE
Can’t be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by gabriel-r** [quentinlesceller/macmediakeyforwarder#5]
Is this normal or something can be done to allow Apple to snitch on it ? 

<img width="260" alt="Screenshot 2022-09-19 at 13 14 13 Applications@2x" src="https://user-images.githubusercontent.com/51084/191005582-5da556a0-61a8-4312-9630-e2d7e6520ed9.png">

**Comment by oof2win2** [comment]
Open system preferences -> Security & Privacy -> General and allow it from there.

**Comment by gabriel-r** [comment]
I know how to run it, thanks :-)

I'm report the issue that it can't be checked by Apple.

**Comment by Splendorr** [comment]
Same issue. Can't find a way to trick the app into opening :(

**Comment by quentinlesceller** [comment]
Yes, this is totally normal behaviour.
