### ISSUE TITLE
3.1.2 broken in Sonoma

### ISSUE THREAD

**Issue by KibosJ** [quentinlesceller/macmediakeyforwarder#9]
I know Sonoma is still in beta, but 3.1.2 asks for the following permissions (even though it already has them) and then quits.

- Automation
- Accessibility

Removing the permissions and re-granting does not work, downgrading to 3.1.1 works.

**Comment by quentinlesceller** [comment]
Interesting. Maybe we should revert the minimum macOS version then.

**Comment by quentinlesceller** [comment]
Reverted. It looks likes lowering the minimum macOS version breaks the app. I'm going to mark the minimum as 12.3.

**Comment by quentinlesceller** [comment]
Okay after additional testing v3.1.2 works. It might not work on Sonoma. But since it is in beta I'd consider this as unsupported for now. We reinvestigate in September when we have the public release.

**Comment by jbleuzen** [comment]
Hi, 
I have the same issue with v3.1.2 on "official" Sonoma v14.0
Downgrading to 3.1.1 make the app works and I'm ok with that for now !
Just so you know…

**Comment by KibosJ** [comment]
Removing all of the permissions for the app, then re-adding them fixed this for me

**Comment by jbleuzen** [comment]
Oh, I didn't know that removing and toggling were 2 differents things.
Thanks it works now with latest version 3.1.2
